### ISSUE TITLE
为什么不使用jsx呢？基于什么考虑呢

### ISSUE THREAD

**Issue by lenxeon** [teambition/react-lite-layered#5]

**Comment by tiye** [comment]
- CoffeeScript 一切皆是表达式, 组合元素更方便
- 重复代码更少
- 官方其实也在推荐 CoffeeScript https://www.npmjs.com/package/react-dom#coffeescript-bliss
- 公司内部以往主要语言是 CoffeeScript

当然不足有
- 不是社区标准的用法, 使用不广泛
- CoffeeScript 未来语法特性增加不会跟上 ES6

考虑到组件主要是公司内部使用, 目前继续沿用 CoffeeScript.
另外我个人偏爱缩进语法, ES6 语法的冗余太多, 我会谨慎使用.
